server:
  port: 80
  servlet:
    context-path: /usinsa

spring:
  ### DB Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/usinsa?useUnicode=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: ssafy

  ### JPA Config
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL57Dialect

  # Spring Boot 2.6 이상 <-> SWAGGER 라이브러리 버전 관리
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # 페이징 - 한 페이지당 아이템 개수
  data:
    web:
      pageable:
        default-page-size: 10

  # JWT Config
  jwt:
    secret: UsinsaSecretKey

  # Email Config
  mail:
    host: smtp.gmail.com
    port: 587
    username: ktechjh@gmail.com
    password: wndguq123!
    protocol: smtp
    properties:
      mail:
        smtp:
          starttls:
            enable: true

  # OAuth2 Config
  oauth:
    kakao:
      client_id: b9a353c2465b3e66d9a03c38beb06053
      secret: w9LT2v0sSHinYZ2wi7NCUc57SSybtwIq
      url:
        token: https://kauth.kakao.com/oauth/token
        profile: https://kapi.kakao.com/v2/user/me
        redirect: http://localhost/linkmix/api/v1/oauth/kakao/login

    google:
      client_id: 950408677651-veaac23nvfspgrh6o5nplvj1epc8iqkb.apps.googleusercontent.com
      secret: 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
      api_key: AIzaSyDKMsDt8OSQudVhvvw3Lr2QN54M3-e_aNA
      scope: profile,email,openid
      url:
        auth: https://oauth2.googleapis.com
        login: https://accounts.google.com
        redirect: http://localhost/linkmix/api/v1/oauth/google/login/redirect

    naver:
      client_id: RdHe5WA3b0DxpXN6JlqX
      secret: AY043mRIQ6
      url:
        profile: https://openapi.naver.com/v1/nid/me
        redirect: http://localhost/linkmix/api/v1/oauth/naver/login/redirect
        auth: https://nid.naver.com/oauth2.0/authorize
        token: https://nid.naver.com/oauth2.0/token

  # Thymeleaf path
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  # Base URL
  url:
    base: http://localhost

# Minio Config
minio:
  url: http://localhost:9000/
  accessKey: minioadmin
  secretKey: minioadmin
  bucket: usinsa

coolSms:
  api_key: NCS2VAZPKWLVJPE2
  secret: L6FHFMMYESKAL1LES526OCFY4GGURYJQ

logging:
  level:
    root: info
    com.spring.usinsa: debug

# iamport
iamport:
  imp_key: 3722341995673042
  imp_secret: db3141b6f24f2a776551372d2e46d43b2cfa41d90a3368fd6c64330ff97a2a9c88abcc8173b48ff0